<?php
/**
 * @file
 * Module remember_me that allow user to save session for a long time.
 */

use \Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter() for user_login_form.
 */
function remember_me_form_user_login_form_alter(&$form, FormStateInterface $form_state) {
  // Configuration for the remember me checkbox.
  $config = \Drupal::config('remember_me.settings_form');
  $managed = (bool) $config->get('remember_me_managed');
  if (!$managed) {
    return;
  }
  $is_visible = $config->get('remember_me_checkbox_visible');
  $checked = $config->get('remember_me_checkbox');
  $form['remember_me'] = array(
    '#title' => t('Remember me'),
    '#type' => ($is_visible === 1) ? 'checkbox' : 'hidden',
    '#default_value' => $checked,
    '#attributes' => array('tabindex' => 1),
  );
}
